*********************************************APPROACH 1st(BRUTE FORCE)*************************************************

class Solution {// Time:  O(n⁴)                         Space: O(1)  
public:
    int tupleSameProduct(vector<int>& nums) {
        int n = nums.size();

        // Stores the total number of valid tuples found
        int ans = 0;

        // Choose the first element of the first pair
        for (int i = 0; i < n; i++) 
        {
            // Choose the second element of the first pair
            for (int j = 0; j < n; j++) 
            {
                // Choose the first element of the second pair
                for (int k = 0; k < n; k++) 
                {
                    // Choose the second element of the second pair
                    for (int l = 0; l < n; l++) 
                    {
                        // All four indices must be different.
                        // We cannot use the same element twice.
                        //
                        // Example:
                        // i != j  → first pair has different elements
                        // i != k  → i and k are different
                        // i != l  → i and l are different
                        // j != k  → j and k are different
                        // j != l  → j and l are different
                        // k != l  → second pair has different elements
                        if (i != j && i != k && i != l &&
                            j != k && j != l &&
                            k != l) {

                            // Product of the first pair
                            int prod1 = nums[i] * nums[j];

                            // Product of the second pair
                            int prod2 = nums[k] * nums[l];

                            // If both products are equal,
                            // we found one valid tuple:
                            //
                            // nums[i] * nums[j] == nums[k] * nums[l]
                            if (prod1 == prod2) 
                            {
                                ans++;
                            }
                        }
                    }
                }
            }
        }

        // already generate all possible orderings.
        return ans;
    }
};

/*

┌─────────────────────────────────────────┐
│      1726 — Tuple with Same Product     │
├─────────────────────────────────────────┤
│ BRUTE FORCE                             │
│                                         │
│ Choose 4 different indices:             │
│ (i, j, k, l)                            │
│                                         │
│ Check:                                  │
│ nums[i] × nums[j]                       │
│          ==                             │
│ nums[k] × nums[l]                       │
│                                         │
│ All indices must be different:          │
│ i≠j, i≠k, i≠l, j≠k, j≠l, k≠l            │
│                                         │
│ Every ordering is generated by loops,   │
│ so → NO ×8                              │
│                                         │
│ TC: O(n⁴)                               │
│ SC: O(1)                                │
└─────────────────────────────────────────┘

*/

**********************************************APPROACH 2nd(OPTIMAL)**************************************************

class Solution {// TC = O(n²) average                          SC = O(n²) worst case
public:
    int tupleSameProduct(vector<int>& nums) {

        int n = nums.size();

        // HashMap stores:
        // product -> number of pairs that have this product
        //
        // Example:
        // If pairs (2,6) and (3,4) both give product 12:
        // ump[12] = 2
        unordered_map<int, int> ump;

        // Stores the total number of valid tuples
        int ans = 0;

        // Choose the first element of the pair
        for (int i = 0; i < n; i++) 
        {
            // Start from i + 1 so that:
            // 1. We don't use the same index twice
            // 2. We consider each pair only once
            //
            // For example:
            // (2,6) is considered
            // (6,2) is NOT considered separately
            for (int j = i + 1; j < n; j++) 
            {
                // Calculate the product of the current pair
                int product = nums[i] * nums[j];

                // ump[product] tells us how many previous pairs
                // had the same product.
                //
                // Each previous pair + current pair can form
                // 8 different ordered tuples.
                //
                // Therefore:
                // previousPairs * 8 are added to the answer.
                ans += ump[product] * 8;

                // Now store the current pair.
                // If this product already exists, increase its count.
                // Otherwise, create it with frequency 1.
                ump[product]++;
            }
        }

        // Return the total number of valid ordered tuples
        return ans;
    }
};

/*

┌─────────────────────────────────────────┐
│     1726 — Tuple with Same Product      │
├─────────────────────────────────────────┤
│ Generate every pair once:               │
│ for i = 0 → n-1                         │
│ for j = i+1 → n-1                       │
│                                         │
│ product = nums[i] × nums[j]             │
│                                         │
│ HashMap:                                │
│ product → frequency of previous pairs   │
│                                         │
│ Same product found:                     │
│ ans += frequency × 8                    │
│                                         │
│ Why ×8?                                 │
│ 2 pair orders × 2 pair orders ×         │
│ 2 ways to arrange the pairs = 8         │
│                                         │
│ TC: O(n²) average                       │
│ SC: O(n²) worst case                    │
└─────────────────────────────────────────┘

*/
